openapi: 3.0.1
info:
  title: 统一告警
  description: ''
  version: 1.0.0
paths:
  /api/venus/v1/alert/details/{id}:
    get:
      summary: 获得告警详情
      deprecated: false
      description: '通过告警数据的主键ID获取告警详情，主要包括告警正文、告警指标、相关业务系统等信息'
      operationId: getAlertDetailsByAlertIDUsingGET
      parameters:
        - name: id
          in: path
          description: 主键ID
          required: true
          example: ''
          schema:
            type: integer
        - name: Authorization
          in: header
          description: 登录token
          required: false
          example: Bearer {{token}}
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ResponseOfAlertVO
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
      x-run-in-apifox: https://apifox.com/web/project/2797460/apis/api-85031881-run
  /api/venus/v1/alert/trace/{id}:
    post:
      summary: 通过告警数据主键，获取某个告警的处理轨迹，即历史的告警操作列表，列表中每一个操作包含告警开始和恢复时间、操作类型、告警状态等信息
      deprecated: false
      description: ''
      operationId: getAlertTraceUsingPOST
      parameters:
        - name: id
          in: path
          description: 主键id
          required: true
          example: ''
          schema:
            type: integer
        - name: Authorization
          in: header
          description: 登录token
          required: false
          example: Bearer {{token}}
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertOpRecordSearchDTO'
            example: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ResponseOfListOfAlertOpRecordVo
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
      x-run-in-apifox: https://apifox.com/web/project/2797460/apis/api-85031900-run
  /api/venus/v1/analysis/record/{id}:
    get:
      summary: 通过告警的配置ID查询相关分析结果，主要包含分析的状态、开始结束时间、分析的报表对象、报表的开始结束时间等信息
      deprecated: false
      description: ''
      operationId: oneUsingGET
      parameters:
        - name: id
          in: path
          description: 配置id
          required: true
          example: ''
          schema:
            type: integer
        - name: Authorization
          in: header
          description: 登录token
          required: false
          example: Bearer {{token}}
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/ResponseOfAnalysisRecordVO
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apifox-orders: []
                x-apifox-ignore-properties: []
      x-run-in-apifox: https://apifox.com/web/project/2797460/apis/api-85032300-run
components:
  schemas:
    ResponseOfAnalysisRecordVO:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: 错误码
          example: 0
        data:
          $ref: '#/components/schemas/AnalysisRecordVO'
          description: 告警分析详情
        msg:
          type: string
          description: 错误信息
          example: success
      title: 响应«AnalysisRecordVO»
      x-apifox-orders:
        - code
        - data
        - msg
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    AnalysisRecordVO:
      type: object
      properties:
        analysisAlertConditionDTO:
          $ref: >-
            #/components/schemas/TimeRangeParams
        analysisEndTime:
          type: integer
          format: int64
          description: 分析结束时间
        analysisStartTime:
          type: integer
          format: int64
          description: 分析开始时间
        analysisStatus:
          type: string
          description: 分析状态
        name:
          type: string
          description: 名称
        report:
          type: object
          x-apifox-orders: []
          properties: {}
          x-apifox-ignore-properties: []
          description: 报表对象
        reportEndTime:
          type: integer
          format: int64
          description: 报表结束时间
        reportId:
          type: string
          description: 报表ID
        reportStartTime: 
          type: integer
          format: int64
          description: 报表开始时间
      title: AnalysisRecordVO
      x-apifox-orders:
        - analysisAlertConditionDTO
        - analysisEndTime
        - analysisStartTime
        - analysisStatus
        - name
        - report
        - reportEndTime
        - reportId
        - reportStartTime
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    TimeRangeParams:
      type: object
      properties:
        firstOccurrenceTimeRange:
          type: array
          description: 时间绝对范围
          items:
            type: integer
            format: int64
        pastMinutes:
          type: integer
          format: int32
          description: 过去几分钟
        relativeInterval:
          type: integer
          format: int32
          description: 相对刷新间隔
        timeRangeTypeEnum:
          type: string
          description: 时间类型
          enum:
            - ABSOLUTE
            - RELATIVE
      title: 时间范围参数，没有配置不传
      x-apifox-orders:
        - firstOccurrenceTimeRange
        - pastMinutes
        - relativeInterval
        - timeRangeTypeEnum
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    ResponseOfListOfAlertOpRecordVo:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: 错误码
          example: 0
        data:
          type: array
          description: 告警轨迹数据
          items:
            $ref: '#/components/schemas/AlertOpRecordVo'
        msg:
          type: string
          description: 错误信息
          example: success
      title: 响应«List«AlertOpRecordVo»»
      x-apifox-orders:
        - code
        - data
        - msg
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    AlertOpRecordVo:
      type: object
      properties:
        alertId:
          type: string
          description: alert告警数据表的ID
        alertLevel:
          type: integer
          format: int32
          description: 级别数字越大级别越高, 允许扩展(0:未知, 1:预警, 2:次要, 3.主要, 4.严重）
        alertStatus:
          type: integer
          format: int32
          description: 告警状态 1故障, 2恢复
        createTime:
          type: integer
          format: int64
          description: 创建时间
        createUser:
          type: string
          description: 创建人
        firstOccurrenceTime:
          type: integer
          format: int64
          description: 首次发生时间
        id:
          type: string
          description: 主键
        opType:
          type: integer
          format: int32
          description: 操作类型
        processStatus:
          type: integer
          format: int32
          description: 告警状态  0打开  1确认  2 关闭
        recoveryTime:
          type: integer
          format: int64
          description: 告警恢复时间
        remark:
          type: string
          description: 备注
      title: AlertOpRecordVo
      x-apifox-orders:
        - alertId
        - alertLevel
        - alertStatus
        - createTime
        - createUser
        - firstOccurrenceTime
        - id
        - opType
        - processStatus
        - recoveryTime
        - remark
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    AlertOpRecordSearchDTO:
      type: object
      properties:
        createTime:
          $ref: '#/components/schemas/ConditionItemDTO'
        createUser:
          type: array
          items:
            type: string
        opType:
          type: array
          items:
            type: integer
            format: int32
        query:
          type: string
      title: AlertOpRecordSearchDTO
      x-apifox-orders:
        - createTime
        - createUser
        - opType
        - query
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    ConditionItemDTO:
      type: object
      properties:
        fieldName:
          type: string
          description: 字段名
        fieldOp:
          type: string
          description: 字段操作符
        fieldType:
          type: string
          description: 字段类型
        fieldValue:
          type: object
          description: 字段值
          x-apifox-orders: []
          properties: {}
          x-apifox-ignore-properties: []
      title: ConditionItemDTO
      x-apifox-orders:
        - fieldName
        - fieldOp
        - fieldType
        - fieldValue
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    ResponseOfAlertVO:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: 错误码
          example: 0
        data:
          $ref: '#/components/schemas/AlertVO'
        msg:
          type: string
          description: 错误信息
          example: success
      title: 响应«告警VO»
      x-apifox-orders:
        - code
        - data
        - msg
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
    AlertVO:
      type: object
      properties:
        aggregationGroup:
          type: integer
          format: int32
          description: 聚合组
        aggregationIdentifier:
          type: string
          description: 聚合组的唯一标识
        aggregationLevel:
          type: integer
          format: int32
          description: 聚合层级默认1, 1父类, 2子类
        aggregationLock:
          type: integer
          format: int32
          description: 聚合锁
        aggregationNum:
          type: integer
          format: int32
          description: 记录聚合子告警数
        alertKey:
          type: string
          description: 监控指标:cpu使用率、内存使用率等
        alertLevel:
          type: integer
          format: int32
          description: 级别数字越大级别越高, 允许扩展(0:未知, 1:预警, 2:次要, 3.主要, 4.严重）
        alertStatus:
          type: integer
          format: int32
          description: 告警状态 1故障, 2恢复
        alertValue:
          type: string
          description: 指标值
        business:
          type: string
          description: 业务系统
        businessShort:
          type: string
          description: 业务系统简称
        category:
          type: string
          description: 监控分类：操作系统、数据库、中间件等
        closeTime:
          type: integer
          format: int64
          description: 关闭时间
        compressGroup:
          type: integer
          format: int32
          description: 压缩组
        compressIdentifier:
          type: string
          description: 压缩组的唯一标识
        compressLevel:
          type: integer
          format: int32
          description: 压缩层级默认1，1父类，2子类
        compressLock:
          type: integer
          format: int32
          description: 压缩锁
        compressNum:
          type: integer
          format: int32
          description: 记录压缩子告警数
        confirmDuration:
          type: integer
          format: int64
          description: 告警确认时长（单位：毫秒)
        confirmTime:
          type: integer
          format: int64
          description: 确认时间
        createTime:
          type: integer
          format: int64
          description: 数据入库时间
        dataCenter:
          type: string
          description: 数据对应的数据中心
        dataSource:
          type: string
          description: 数据来源标志
        dataType:
          type: integer
          format: int32
          description: 1.正常告警  2 过滤告警 3 无效告警
        dimension:
          type: string
          description: 维度
        firstOccurrenceTime:
          type: integer
          format: int64
          description: 首次发生时间
        flowEndTime:
          type: integer
          format: int64
          description: 流程处理结束时间
        flowStatus:
          type: integer
          format: int32
          description: 流程状态 0流程结束 1流程中
        id:
          type: string
          description: 告警表唯一ID
        identifier:
          type: string
          description: 告警唯一标识
        itsmFlag:
          type: integer
          format: int32
          description: 工单标志 (0:未转工单,1:已转工单)
        lastOccurrenceTime:
          type: integer
          format: int64
          description: 最后发生时间
        maintenanceFlag:
          type: integer
          format: int32
          description: 维护期标志  (0:不属于维护期,1:维护期内)
        misreportFlag:
          type: integer
          format: int32
          description: 误报标志 0 非误报  1 误报
        monitorObject:
          type: string
          description: 监控对象(定位告警指标-对应指标维度)如单机多个oracle, 其中一个实例
        node:
          type: string
          description: 故障发生对象的IP
        nodeAlias:
          type: string
          description: 故障发生的主机名
        noticeFlag:
          type: integer
          format: int32
          description: 通知状态标志 0 无通知 1 通知有成功 2 通知从未成功
        object:
          type: string
          description: 对象类(探针类型)指:cpu_total、/home、disk1、表空间1
        objectClass:
          type: string
          description: 对象类(探针类型)的分类:cpu、filesystem、磁盘、数据库实例1
        occurrenceNum:
          type: integer
          format: int32
          description: occurrenceNum 发生次数
        openDuration:
          type: integer
          format: int64
          description: 告警打开时长(单位：毫秒)
        processDuration:
          type: integer
          format: int64
          description: 告警人工处理时长(单位：毫秒)
        processStatus:
          type: integer
          format: int32
          description: 告警处理状态  0打开  1确认  2 关闭
        recoveryDuration:
          type: integer
          format: int64
          description: 告警持续时长(单位:毫秒)
        recoveryTime:
          type: integer
          format: int64
          description: 告警恢复时间
        reportTime:
          type: integer
          format: int64
          description: 底层上报时间(发到接收中间件的时间)
        summary:
          type: string
          description: 告警正文
        tag:
          type: string
          description: 标签
        transmissionDuration:
          type: integer
          format: int64
          description: 告警传输时长(单位:毫秒)
        updateTime:
          type: integer
          format: int64
          description: 数据最后更新时间
        userGroup:
          type: string
          description: 联系人用户组
        userName:
          type: string
          description: 联系人用户名
        userRemark:
          type: string
          description: 处理人备注
      title: 告警VO
      x-apifox-orders:
        - aggregationGroup
        - aggregationIdentifier
        - aggregationLevel
        - aggregationLock
        - aggregationNum
        - alertKey
        - alertLevel
        - alertStatus
        - alertValue
        - business
        - businessShort
        - category
        - closeTime
        - compressGroup
        - compressIdentifier
        - compressLevel
        - compressLock
        - compressNum
        - confirmDuration
        - confirmTime
        - createTime
        - dataCenter
        - dataSource
        - dataType
        - dimension
        - firstOccurrenceTime
        - flowEndTime
        - flowStatus
        - id
        - identifier
        - itsmFlag
        - lastOccurrenceTime
        - maintenanceFlag
        - misreportFlag
        - monitorObject
        - node
        - nodeAlias
        - noticeFlag
        - object
        - objectClass
        - occurrenceNum
        - openDuration
        - processDuration
        - processStatus
        - recoveryDuration
        - recoveryTime
        - reportTime
        - summary
        - tag
        - transmissionDuration
        - updateTime
        - userGroup
        - userName
        - userRemark
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
servers:
  - url: http://10.0.80.239:8088
    description: 风险中心
